robot_base_frame: base_link
global_frame: odom
update_frequency: 10.0
publish_frequency: 5.0
transform_tolerance: 0.1
footprint: [[-0.2,-0.2],[0.2,-0.2],[0.2,0.2],[-0.2,0.2]]
inflation_radius: 0.3
obstacle_range: 2.5
raytrace_range: 3.0
