footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]
# robot_radius: 0.2 # Use this if your robot is circular

obstacle_layer:
  enabled: true
  obstacle_range: 2.5
  raytrace_range: 3.0
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

inflation_layer:
  enabled: true
  inflation_radius: 0.5
  cost_scaling_factor: 10.0