global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true
  plugins:
    - name: static_layer
      type: "costmap_2d::StaticLayer"
    - name: obstacle_layer
      type: "costmap_2d::ObstacleLayer"
      observation_sources: laser_scan_sensor
      laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"
      inflation_radius: 0.3