local_costmap:
  global_frame: odom          # Important: use odom for local planning
  robot_base_frame: base_link # Or base_footprint
  
  update_frequency: 5.0       # How often to calculate the map (Hz)
  publish_frequency: 2.0      # How often to send to Rviz
  
  static_map: false           # Local map is NOT static
  rolling_window: true        # The map "follows" the robot
  width: 3.0                  # Size of the window in meters
  height: 3.0
  resolution: 0.05            # Accuracy (0.05m = 5cm per pixel)

  plugins:
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}